// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcqLSkAezaxhXN04STsFpr6g0nTPDGT8w',
    appId: '1:420623359449:web:4071ea18cfe4e424f40dc8',
    messagingSenderId: '420623359449',
    projectId: 'project1-20337',
    authDomain: 'project1-20337.firebaseapp.com',
    storageBucket: 'project1-20337.firebasestorage.app',
    measurementId: 'G-VGBGH9DGFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcK3v6HlG5RVDo9fZAJjbJ-Sw-bNxD8jU',
    appId: '1:420623359449:android:cedb8bacde7db254f40dc8',
    messagingSenderId: '420623359449',
    projectId: 'project1-20337',
    storageBucket: 'project1-20337.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvwupH6faM1xa1OzPDqFHw0Y9cd_2vCfg',
    appId: '1:420623359449:ios:3bbc836c6a8283ecf40dc8',
    messagingSenderId: '420623359449',
    projectId: 'project1-20337',
    storageBucket: 'project1-20337.firebasestorage.app',
    iosBundleId: 'com.example.belajarFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvwupH6faM1xa1OzPDqFHw0Y9cd_2vCfg',
    appId: '1:420623359449:ios:3bbc836c6a8283ecf40dc8',
    messagingSenderId: '420623359449',
    projectId: 'project1-20337',
    storageBucket: 'project1-20337.firebasestorage.app',
    iosBundleId: 'com.example.belajarFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcqLSkAezaxhXN04STsFpr6g0nTPDGT8w',
    appId: '1:420623359449:web:1765a22a6e46abacf40dc8',
    messagingSenderId: '420623359449',
    projectId: 'project1-20337',
    authDomain: 'project1-20337.firebaseapp.com',
    storageBucket: 'project1-20337.firebasestorage.app',
    measurementId: 'G-EK7L0M7QRY',
  );
}
